# Generated by Django 4.2.4 on 2023-08-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
    ]
