# Generated by Django 4.2.4 on 2023-08-14 06:02

from django.db import migrations, models
import resume.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, default='', storage=resume.custom_storage.DocumentStorage(), upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='file',
            field=models.ImageField(blank=True, default='', storage=resume.custom_storage.ImageSettingStorage(), upload_to='', verbose_name='Image'),
        ),
    ]
